version: "3"

services:
  ldap:
    image: nitnelave/lldap:latest-alpine
    container_name: ldap
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hp1-network
    labels:
      traefik.enable: true
      traefik.http.routers.ldap.entrypoints: https
      traefik.http.services.ldap.loadbalancer.server.port: 17170
    volumes:
      - ./config:/data
    environment:
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET:?error}
      LLDAP_LDAP_USER_PASS: ${LLDAP_LDAP_USER_PASS:?error}
      LLDAP_SMTP_OPTIONS_PASSWORD: ${LLDAP_SMTP_OPTIONS_PASSWORD:?error}
      LLDAP_DATABASE_URL: ${LLDAP_DATABASE_URL:?error}
    # ports:
    #   - 389:389

networks:
  hp1-network:
    driver: bridge
    external: true
