version: "3"

services:
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
      NOTIFICATION_URLS: smtp://castelnuovo/production:secret@mx.email.castelnuovo.dev:25/?fromAddress=backup@email.castelnuovo.dev&toAddresses=luca@castelnuovo.dev
    volumes:
      - ./backups:/archive
      - data:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  data:
