version: v3

teleport:
  nodename: teleport.castelnuovo.dev
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  cluster_name: teleport.castelnuovo.dev
  public_addr: teleport.castlenuovo.dev:443
  proxy_listener_mode: multiplex
  authentication:
    type: local
    # second_factor: otp
    # require_session_mfa: yes

proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
