version: v3

teleport:
  nodename: teleport.castelnuovo.dev
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  cluster_name: teleport.castelnuovo.dev
  public_addr: teleport.castlenuovo.dev:3025
  proxy_listener_mode: separate
  authentication:
    type: local
    second_factor: otp
    require_session_mfa: yes

ssh_service:
  enabled: "no"

proxy_service:
  enabled: "yes"
  public_addr: teleport.castelnuovo.dev:443
  ssh_public_addr: teleport.castelnuovo.dev:3023
  tunnel_public_addr: teleport.castelnuovo.dev:3024
  https_keypairs: []
  acme: {}
