version: v3

teleport:
  nodename: teleport.castelnuovo.dev
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  cluster_name: teleport.castelnuovo.dev
  public_addr: teleport.castlenuovo.dev:3025
  proxy_listener_mode: multiplex
  # listen_addr: 0.0.0.0:3025
  # message_of_the_day: "Opbokken"
  authentication:
    type: local
    # second_factor: otp

proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
