http:
  routers:
    nas:
      entryPoints:
        - https
      rule: "Host(`nas.castelnuovo.dev`)"
      service: nas

    hp1:
      entryPoints:
        - https
      rule: "Host(`hp1.castelnuovo.dev`)"
      service: hp1

    hp2:
      entryPoints:
        - https
      rule: "Host(`hp2.castelnuovo.dev`)"
      service: hp2

    mail:
      entryPoints:
        - https
      rule: "Host(`mail.castelnuovo.dev`)"
      service: mail

    invoice:
      entryPoints:
        - https
      rule: "Host(`invoice.castelnuovo.dev`)"
      service: invoice

  services:
    nas:
      loadBalancer:
        servers:
          - url: https://nas.device.castelnuovo.dev:5001

    hp1:
      loadBalancer:
        servers:
          - url: https://hp1.device.castelnuovo.dev:8006

    hp2:
      loadBalancer:
        servers:
          - url: https://hp2.device.castelnuovo.dev:8006

    mail:
      loadBalancer:
        servers:
          - url: http://mail.vm.castelnuovo.dev

    invoice:
      loadBalancer:
        servers:
          - url: http://invoice.vm.castelnuovo.dev

  middlewares:
    auth:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://authelia.castelnuovo.dev/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    securityHeaders:
      headers:
        customResponseHeaders:
          server: ""
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
        referrerPolicy: same-origin
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: SAMEORIGIN
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
        # permissionsPolicy: ""

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
