version: "3"

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hp1-network
    volumes:
      - ./mariadb:/config
    environment:
      TZ: Europe/Amsterdam
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?error}
    ports:
      - 3306:3306

hp1-network:
  database-net:
    driver: bridge
    external: true
