version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    # restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_TO: luca@castelnuovo.dev
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: watchtower@mail.castelnuovo.dev
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: mail.castelnuovo.dev
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: castelnuovo/production
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_MAIL_PASSWORD:?error}
