version: "3"

services:
  invoices:
    image: lucacastelnuovo/invoices:latest
    container_name: invoices
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hp1-network
    labels:
      traefik.enable: true
      traefik.http.routers.invoices.entrypoints: https
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://invoices.castelnuovo.dev

      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: db_invoices
      DB_USERNAME: user_invoices
      DB_PASSWORD: ${INVOICES_DB_PASSWORD:?error}

      MAIL_HOST: mail.castelnuovo.dev
      MAIL_PORT: 25
      MAIL_USERNAME: castelnuovo/production
      MAIL_PASSWORD: ${INVOICES_MAIL_PASSWORD:?error}
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: invoices@mail.castelnuovo.dev
      MAIL_FROM_NAME: Castelnuovo Development

      SANCTUM_STATEFUL_DOMAINS: invoices.castelnuovo.dev
      SESSION_DOMAIN: invoices.castelnuovo.dev

networks:
  hp1-network:
    driver: bridge
    external: true
