version: "2.1"

services:
  snipe:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hp1-network
    labels:
      traefik.enable: true
      traefik.http.routers.snipe.entrypoints: https
    volumes:
      - ./data:/config
    environment:
      TZ: Europe/Amsterdam

      APP_ENV: production
      APP_DEBUG: false
      APP_LOCALE: nl
      APP_URL: https://snipe.castelnuovo.dev

      MYSQL_PORT_3306_TCP_ADDR: mariadb
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_DATABASE: db_snipe
      MYSQL_USER: user_snipe
      MYSQL_PASSWORD: ${SNIPE_DB_PASSWORD:?error}

      MAIL_PORT_587_TCP_ADDR: mail.vm.castelnuovo.dev
      MAIL_PORT_587_TCP_PORT: 25
      MAIL_ENV_USERNAME: castelnuovo/production
      MAIL_ENV_PASSWORD: ${SNIPE_MAIL_PASSWORD:?error}
      MAIL_ENV_ENCRYPTION: tls
      MAIL_ENV_FROM_ADDR: snip@mail.castelnuovo.dev
      MAIL_ENV_FROM_NAME: Snipe

networks:
  hp1-network:
    driver: bridge
    external: true
