version: "3"

services:
  reinaert:
    image: zidreinaert/api:latest
    container_name: reinaert
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.reinaert.entrypoints: https
      traefik.http.services.reinaert.loadbalancer.server.port: 80
    volumes:
      - ./creds:/var/www/html/creds
    environment:
      app_url: https://reinaert.castelnuovo.dev
      cron_key: ${CRON_KEY:?error}

networks:
  traefik-proxy:
    driver: bridge
    external: true
