version: "3"

services:
  vosstraat:
    image: lucacastelnuovo/vosstraat:latest
    container_name: vosstraat
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.vosstraat.entrypoints: https
      traefik.http.services.vosstraat.loadbalancer.server.port: 80
    environment:
      JWT_KEY: ${JWT_KEY:?error}

networks:
  traefik-proxy:
    driver: bridge
    external: true
