version: "3"

services:
  s3:
    image: minio/minio:latest
    container_name: s3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hp1-network
    labels:
      traefik.enable: true

      traefik.http.routers.s3.entrypoints: https
      traefik.http.routers.s3.rule: Host(`s3.castelnuovo.dev`)
      traefik.http.routers.s3.service: s3
      traefik.http.services.s3.loadbalancer.server.port: 9000

      traefik.http.routers.s3-console.entrypoints: https
      traefik.http.routers.s3-console.rule: Host(`s3-console.castelnuovo.dev`)
      traefik.http.routers.s3-console.service: s3-console
      traefik.http.services.s3-console.loadbalancer.server.port: 9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_SERVER_URL: https://s3.castelnuovo.dev
      MINIO_BROWSER_REDIRECT_URL: https://s3-console.castelnuovo.dev

      MINIO_IDENTITY_LDAP_SERVER_ADDR: ldap:389
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: cn=admin,ou=people,dc=castelnuovo,dc=dev
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: ou=people,dc=castelnuovo,dc=dev
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: (uid=%s)
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: ${MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD:?error}
      MINIO_IDENTITY_LDAP_SERVER_INSECURE: on
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

networks:
  hp1-network:
    driver: bridge
    external: true
