version: "3"

services:
  s3:
    image: minio/minio
    container_name: s3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true

      traefik.http.routers.s3.entrypoints: https
      traefik.http.routers.s3.rule: Host(`s3.castelnuovo.dev`)
      traefik.http.routers.s3.service: s3
      traefik.http.services.s3.loadbalancer.server.port: 9000

      traefik.http.routers.s3-console.entrypoints: https
      traefik.http.routers.s3-console.rule: Host(`s3-console.castelnuovo.dev`)
      traefik.http.routers.s3-console.service: s3-console
      traefik.http.services.s3-console.loadbalancer.server.port: 9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_SERVER_URL: https://s3.castelnuovo.dev
      MINIO_BROWSER_REDIRECT_URL: https://s3-console.castelnuovo.dev

      MINIO_IDENTITY_LDAP_SERVER_ADDR: ldap:389
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: cn=admin,dc=castelnuovo,dc=xyz
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: ou=people,dc=castelnuovo,dc=xyz
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: (uid=%s)
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: ${MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD:?error}
      MINIO_IDENTITY_LDAP_SERVER_INSECURE: on

      # MINIO_KMS_KES_ENDPOINT: https://s3-kes:7373
      # MINIO_KMS_KES_CAPATH: /kes/server.crt
      # MINIO_KMS_KES_KEY_FILE: /kes/client.key
      # MINIO_KMS_KES_CERT_FILE: /kes/client.crt
      # MINIO_KMS_KES_KEY_NAME: default-key
    volumes:
      - ./s3-kes:/kes
      - ./s3-minio:/data
    command: server /data --console-address ":9001"

  s3-kes:
    image: minio/kes:latest
    container_name: s3-kes
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    environment:
      KES_IDENTITY: ${KES_IDENTITY:?error}
      KES_APPROLE_ID: ${KES_APPROLE_ID:?error}
      KES_APPROLE_SECRET: ${KES_APPROLE_SECRET:?error}
    volumes:
      - ./s3-kes:/root/.kes
    command: server --config=/root/.kes/config.yml --auth=off

networks:
  traefik-proxy:
    driver: bridge
    external: true
