version: "3"

services:
  mail:
    image: bytemark/smtp:latest
    restart: unless-stopped
    networks:
      - stats-network

  stats_db:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - stats-network
    volumes:
      - ./data/stats_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats_events:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: unless-stopped
    networks:
      - stats-network
    volumes:
      - ./data/stats_events:/var/lib/clickhouse
      - ./config/config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./config/user.xml:/etc/clickhouse-server/users.d/logging.xml:ro

  stats:
    image: plausible/analytics:latest
    container_name: stats
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - stats-network
      - hp1-network
    labels:
      traefik.enable: true
      traefik.http.routers.stats.entrypoints: https
      traefik.http.services.stats.loadbalancer.server.port: 8000
    environment:
      BASE_URL: https://stats.castelnuovo.dev
      DATABASE_URL: postgres://postgres:postgres@stats_db/plausible_db
      CLICKHOUSE_DATABASE_URL: http://stats_events:8123/plausible_events_db
      SECRET_KEY_BASE: ${STATS_KEY:?error}
      DISABLE_REGISTRATION: true
      MAILER_EMAIL: stats@mail.castelnuovo.dev
      SMTP_HOST_ADDR: mail.vm.castelnuovo.dev
      SMTP_USER_NAME: castelnuovo/production
      SMTP_USER_PWD: ${STATS_MAIL_PASSWORD:?error}
      SMTP_HOST_SSL_ENABLED: true
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - stats_db
      - stats_events
      - mail

networks:
  stats-network:
    driver: bridge
    external: false
  hp1-network:
    driver: bridge
    external: true
